version: '2'
services:
    karappatan-app:
        image: karappatan
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://karappatan-postgresql:5432/karappatan
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    karappatan-postgresql:
        extends:
            file: postgresql.yml
            service: karappatan-postgresql
