version: '2'
services:
    karappatan-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/karappatan/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=karappatan
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
